name: Deploy Next.js SSG to Separate Branch

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to your 'main' branch
  workflow_dispatch: {} # ADD THIS LINE. Allows manual/API triggering.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # The environment where the job will run

    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Action to set up Node.js
        with:
          node-version: '20' # Specify the Node.js version your project uses
          cache: 'npm'       # Caches npm dependencies to speed up builds

      - name: Install Dependencies
        run: npm ci # 'npm ci' is preferred over 'npm install' in CI environments for clean installs

      - name: Build Next.js SSG Project
        run: npm run build # Runs the 'build' script defined in your package.json

      - name: Deploy to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v3 # A popular action for deploying to gh-pages
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }} # GitHub's built-in token for authentication
          publish_dir: ./out # The directory containing your static build output
          commit_message: "🚀 Deploying from main branch - Commit ${{ github.sha }}" # Custom message

          # publish_branch: gh-pages # Default. You can change this if you want a different branch name (e.g., 'dist')
          # force_orphan: true # Uncomment this if you want to completely overwrite the branch history each time
                             # This keeps the history of the deploy branch very clean but loses past commits.